"""Fresh schema: core tables only, no compression

Revision ID: 8353946bb7d5
Revises: 
Create Date: 2025-11-16 09:18:50.477345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8353946bb7d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('backtest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.String(length=50), nullable=False),
    sa.Column('strategy_description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('annualized_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_duration', sa.Integer(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('value_at_risk_95', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('conditional_var_95', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('executed_by', sa.String(length=100), nullable=True),
    sa.Column('execution_time', sa.Interval(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('fees_included', sa.Boolean(), nullable=True),
    sa.Column('slippage_included', sa.Boolean(), nullable=True),
    sa.CheckConstraint('end_date > start_date', name='chk_date_order'),
    sa.CheckConstraint('total_trades >= 0 AND winning_trades >= 0 AND losing_trades >= 0', name='chk_trade_counts'),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_index('idx_backtest_strategy', 'backtest_results', ['strategy_name', 'strategy_version', 'executed_at'], unique=False)
    op.create_index(op.f('ix_backtest_results_executed_at'), 'backtest_results', ['executed_at'], unique=False)
    op.create_index(op.f('ix_backtest_results_sharpe_ratio'), 'backtest_results', ['sharpe_ratio'], unique=False)
    op.create_index(op.f('ix_backtest_results_strategy_name'), 'backtest_results', ['strategy_name'], unique=False)
    op.create_table('market_calendar',
    sa.Column('calendar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', postgresql.ENUM('US', 'CRYPTO', 'FOREX', 'COMMODITIES', name='market_enum'), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('holiday_name', sa.String(length=100), nullable=True),
    sa.Column('open_time', sa.Time(timezone=True), nullable=True),
    sa.Column('close_time', sa.Time(timezone=True), nullable=True),
    sa.Column('is_early_close', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('calendar_id'),
    sa.UniqueConstraint('date', 'market', name='uq_calendar_date_market')
    )
    op.create_index('idx_market_calendar_holidays', 'market_calendar', ['date'], unique=False, postgresql_where=sa.text('is_holiday = true'))
    op.create_index(op.f('ix_market_calendar_date'), 'market_calendar', ['date'], unique=False)
    op.create_table('ml_models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('model_hash', sa.String(length=64), nullable=True),
    sa.Column('training_start_date', sa.Date(), nullable=True),
    sa.Column('training_end_date', sa.Date(), nullable=True),
    sa.Column('validation_start_date', sa.Date(), nullable=True),
    sa.Column('validation_end_date', sa.Date(), nullable=True),
    sa.Column('features_used', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('train_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('validation_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('test_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('mae', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('r2_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('deployed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('retired_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('model_name', 'model_version', name='uq_model_name_version')
    )
    op.create_index('idx_ml_models_deployed', 'ml_models', ['deployed_at'], unique=False, postgresql_where=sa.text("status = 'deployed'"))
    op.create_index(op.f('ix_ml_models_status'), 'ml_models', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('data_type', postgresql.ENUM('ohlcv', 'simple', 'calculated', 'social', 'onchain', 'macro', 'derivative', 'stablecoin', 'etf', 'defi', name='data_type_enum'), nullable=False),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('api_provider', sa.String(length=50), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('update_frequency', sa.Interval(), nullable=False),
    sa.Column('last_successful_update', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('next_scheduled_update', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'deprecated', 'testing', name='plugin_status_enum'), nullable=True),
    sa.Column('market_type', postgresql.ENUM('US', 'CRYPTO', 'FOREX', 'COMMODITIES', name='market_enum'), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("name ~ '^[a-z0-9_]+$'", name='chk_name_format'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index('idx_sources_next_update', 'sources', ['next_scheduled_update'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_sources_category'), 'sources', ['category'], unique=False)
    op.create_index(op.f('ix_sources_data_type'), 'sources', ['data_type'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_table('time_index',
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('date_only', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('is_trading_day_us', sa.Boolean(), nullable=True),
    sa.Column('is_trading_day_crypto', sa.Boolean(), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_time_index_trading_us', 'time_index', ['timestamp'], unique=False, postgresql_where=sa.text('is_trading_day_us = true'))
    op.create_index('idx_time_index_weekend', 'time_index', ['timestamp'], unique=False, postgresql_where=sa.text('is_weekend = true'))
    op.create_index(op.f('ix_time_index_date_only'), 'time_index', ['date_only'], unique=False)
    op.create_table('timeseries_archive',
    sa.Column('archive_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=3), nullable=False),
    sa.Column('date_only', sa.String(), nullable=True),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted_by', sa.String(length=100), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('restored_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('restored_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_index('idx_archive_restorable', 'timeseries_archive', ['source_id', 'timestamp'], unique=False, postgresql_where=sa.text('restored_at IS NULL'))
    op.create_index('idx_archive_source_time', 'timeseries_archive', ['source_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_timeseries_archive_deleted_at'), 'timeseries_archive', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_timeseries_archive_source_id'), 'timeseries_archive', ['source_id'], unique=False)
    op.create_index(op.f('ix_timeseries_archive_timestamp'), 'timeseries_archive', ['timestamp'], unique=False)
    op.create_table('validation_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', postgresql.ENUM('ohlcv', 'simple', 'calculated', 'social', 'onchain', 'macro', 'derivative', 'stablecoin', 'etf', 'defi', name='data_type_enum'), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_sql', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('idx_validation_rules_enabled', 'validation_rules', ['data_type'], unique=False, postgresql_where=sa.text('enabled = true'))
    op.create_index(op.f('ix_validation_rules_data_type'), 'validation_rules', ['data_type'], unique=False)
    op.create_index(op.f('ix_validation_rules_enabled'), 'validation_rules', ['enabled'], unique=False)
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('anomaly_type', postgresql.ENUM('outlier_4sigma', 'outlier_6sigma', 'missing_data', 'late_data', 'corrupt_data', 'duplicate', name='anomaly_type_enum'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('z_score', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('deviation_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_blackswan', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index('idx_anomalies_blackswan', 'anomalies', ['detected_at'], unique=False, postgresql_where=sa.text('is_blackswan = true'))
    op.create_index('idx_anomalies_source_time', 'anomalies', ['source_id', 'timestamp'], unique=False)
    op.create_index('idx_anomalies_unreviewed', 'anomalies', ['detected_at'], unique=False, postgresql_where=sa.text('reviewed = false'))
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_is_blackswan'), 'anomalies', ['is_blackswan'], unique=False)
    op.create_index(op.f('ix_anomalies_reviewed'), 'anomalies', ['reviewed'], unique=False)
    op.create_index(op.f('ix_anomalies_source_id'), 'anomalies', ['source_id'], unique=False)
    op.create_index(op.f('ix_anomalies_timestamp'), 'anomalies', ['timestamp'], unique=False)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('action', postgresql.ENUM('INSERT', 'UPDATE', 'DELETE', 'CORRECTION', name='audit_action_enum'), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('idx_audit_log_source', 'audit_log', ['source_id', 'changed_at'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp', 'changed_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_changed_at'), 'audit_log', ['changed_at'], unique=False)
    op.create_index(op.f('ix_audit_log_changed_by'), 'audit_log', ['changed_by'], unique=False)
    op.create_index(op.f('ix_audit_log_source_id'), 'audit_log', ['source_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('trade_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('exit_timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('position_value', sa.Numeric(precision=30, scale=2), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=30, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=30, scale=2), nullable=False),
    sa.Column('return_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('entry_signal', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name='chk_direction'),
    sa.CheckConstraint('exit_timestamp > entry_timestamp', name='chk_exit_after_entry'),
    sa.CheckConstraint('quantity > 0', name='chk_quantity_positive'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_results.backtest_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('idx_backtest_trades_backtest', 'backtest_trades', ['backtest_id', 'entry_timestamp'], unique=False)
    op.create_index('idx_backtest_trades_duration', 'backtest_trades', ['duration'], unique=False)
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_entry_timestamp'), 'backtest_trades', ['entry_timestamp'], unique=False)
    op.create_index(op.f('ix_backtest_trades_return_pct'), 'backtest_trades', ['return_pct'], unique=False)
    op.create_table('features',
    sa.Column('feature_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('volatility_7d', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volatility_30d', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volatility_90d', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rsi_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rsi_momentum', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_sma_20', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('funding_rate', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('funding_delta', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('basis_spread', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('social_volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('social_sentiment', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('regime_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('custom_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_set_version', sa.String(length=20), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('source_id', 'timestamp', name='uq_features_source_timestamp')
    )
    op.create_index('idx_features_regime', 'features', ['regime'], unique=False, postgresql_where=sa.text('regime IS NOT NULL'))
    op.create_index('idx_features_source_time', 'features', ['source_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_features_source_id'), 'features', ['source_id'], unique=False)
    op.create_index(op.f('ix_features_timestamp'), 'features', ['timestamp'], unique=False)
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('forecast_timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('target_timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('confidence_lower', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('confidence_upper', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('prediction_error', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('absolute_error', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('percentage_error', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('target_timestamp > forecast_timestamp', name='chk_target_future'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index('idx_forecasts_model', 'forecasts', ['model_name', 'created_at'], unique=False)
    op.create_index('idx_forecasts_pending', 'forecasts', ['target_timestamp'], unique=False, postgresql_where=sa.text('actual_value IS NULL'))
    op.create_index('idx_forecasts_source_target', 'forecasts', ['source_id', 'target_timestamp'], unique=False)
    op.create_index(op.f('ix_forecasts_model_name'), 'forecasts', ['model_name'], unique=False)
    op.create_index(op.f('ix_forecasts_source_id'), 'forecasts', ['source_id'], unique=False)
    op.create_index(op.f('ix_forecasts_target_timestamp'), 'forecasts', ['target_timestamp'], unique=False)
    op.create_table('lineage',
    sa.Column('lineage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('derived_source_id', sa.Integer(), nullable=False),
    sa.Column('parent_source_id', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.String(length=50), nullable=False),
    sa.Column('calculation_sql', sa.Text(), nullable=True),
    sa.Column('calculation_function', sa.Text(), nullable=True),
    sa.Column('dependency_level', sa.Integer(), nullable=False),
    sa.Column('refresh_required', sa.Boolean(), nullable=True),
    sa.Column('last_calculation_time', sa.Interval(), nullable=True),
    sa.Column('avg_calculation_time', sa.Interval(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('derived_source_id != parent_source_id', name='chk_no_self_reference'),
    sa.ForeignKeyConstraint(['derived_source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lineage_id'),
    sa.UniqueConstraint('derived_source_id', 'parent_source_id', name='uq_lineage_derived_parent')
    )
    op.create_index('idx_lineage_refresh_needed', 'lineage', ['refresh_required'], unique=False, postgresql_where=sa.text('refresh_required = true'))
    op.create_index(op.f('ix_lineage_derived_source_id'), 'lineage', ['derived_source_id'], unique=False)
    op.create_index(op.f('ix_lineage_parent_source_id'), 'lineage', ['parent_source_id'], unique=False)
    op.create_index(op.f('ix_lineage_refresh_required'), 'lineage', ['refresh_required'], unique=False)
    op.create_table('timeseries_data',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=3), nullable=False),
    sa.Column('date_only', sa.Date(), nullable=True),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('ingestion_timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.CheckConstraint('high >= low', name='chk_high_low'),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 100', name='chk_quality_score'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'timestamp')
    )
    op.create_index('idx_timeseries_anomalies', 'timeseries_data', ['source_id', 'timestamp'], unique=False, postgresql_where=sa.text('is_anomaly = true'))
    op.create_index('idx_timeseries_date', 'timeseries_data', ['date_only'], unique=False)
    op.create_index('idx_timeseries_quality', 'timeseries_data', ['quality_score'], unique=False, postgresql_where=sa.text('quality_score < 80'))
    op.create_index('idx_timeseries_source_time', 'timeseries_data', ['source_id', 'timestamp'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_timeseries_data_is_anomaly'), 'timeseries_data', ['is_anomaly'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeseries_data_is_anomaly'), table_name='timeseries_data')
    op.drop_index('idx_timeseries_source_time', table_name='timeseries_data', postgresql_using='btree')
    op.drop_index('idx_timeseries_quality', table_name='timeseries_data', postgresql_where=sa.text('quality_score < 80'))
    op.drop_index('idx_timeseries_date', table_name='timeseries_data')
    op.drop_index('idx_timeseries_anomalies', table_name='timeseries_data', postgresql_where=sa.text('is_anomaly = true'))
    op.drop_table('timeseries_data')
    op.drop_index(op.f('ix_lineage_refresh_required'), table_name='lineage')
    op.drop_index(op.f('ix_lineage_parent_source_id'), table_name='lineage')
    op.drop_index(op.f('ix_lineage_derived_source_id'), table_name='lineage')
    op.drop_index('idx_lineage_refresh_needed', table_name='lineage', postgresql_where=sa.text('refresh_required = true'))
    op.drop_table('lineage')
    op.drop_index(op.f('ix_forecasts_target_timestamp'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_source_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_model_name'), table_name='forecasts')
    op.drop_index('idx_forecasts_source_target', table_name='forecasts')
    op.drop_index('idx_forecasts_pending', table_name='forecasts', postgresql_where=sa.text('actual_value IS NULL'))
    op.drop_index('idx_forecasts_model', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_features_timestamp'), table_name='features')
    op.drop_index(op.f('ix_features_source_id'), table_name='features')
    op.drop_index('idx_features_source_time', table_name='features')
    op.drop_index('idx_features_regime', table_name='features', postgresql_where=sa.text('regime IS NOT NULL'))
    op.drop_table('features')
    op.drop_index(op.f('ix_backtest_trades_return_pct'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_entry_timestamp'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_index('idx_backtest_trades_duration', table_name='backtest_trades')
    op.drop_index('idx_backtest_trades_backtest', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_source_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_changed_by'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_changed_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_source', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_anomalies_timestamp'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_source_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_reviewed'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_is_blackswan'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_index('idx_anomalies_unreviewed', table_name='anomalies', postgresql_where=sa.text('reviewed = false'))
    op.drop_index('idx_anomalies_source_time', table_name='anomalies')
    op.drop_index('idx_anomalies_blackswan', table_name='anomalies', postgresql_where=sa.text('is_blackswan = true'))
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_validation_rules_enabled'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_data_type'), table_name='validation_rules')
    op.drop_index('idx_validation_rules_enabled', table_name='validation_rules', postgresql_where=sa.text('enabled = true'))
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_timeseries_archive_timestamp'), table_name='timeseries_archive')
    op.drop_index(op.f('ix_timeseries_archive_source_id'), table_name='timeseries_archive')
    op.drop_index(op.f('ix_timeseries_archive_deleted_at'), table_name='timeseries_archive')
    op.drop_index('idx_archive_source_time', table_name='timeseries_archive')
    op.drop_index('idx_archive_restorable', table_name='timeseries_archive', postgresql_where=sa.text('restored_at IS NULL'))
    op.drop_table('timeseries_archive')
    op.drop_index(op.f('ix_time_index_date_only'), table_name='time_index')
    op.drop_index('idx_time_index_weekend', table_name='time_index', postgresql_where=sa.text('is_weekend = true'))
    op.drop_index('idx_time_index_trading_us', table_name='time_index', postgresql_where=sa.text('is_trading_day_us = true'))
    op.drop_table('time_index')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_data_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_category'), table_name='sources')
    op.drop_index('idx_sources_next_update', table_name='sources', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('sources')
    op.drop_index(op.f('ix_ml_models_status'), table_name='ml_models')
    op.drop_index('idx_ml_models_deployed', table_name='ml_models', postgresql_where=sa.text("status = 'deployed'"))
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_market_calendar_date'), table_name='market_calendar')
    op.drop_index('idx_market_calendar_holidays', table_name='market_calendar', postgresql_where=sa.text('is_holiday = true'))
    op.drop_table('market_calendar')
    op.drop_index(op.f('ix_backtest_results_strategy_name'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_sharpe_ratio'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_executed_at'), table_name='backtest_results')
    op.drop_index('idx_backtest_strategy', table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
